server:
  port: 8788
spring:
  application:
    name: ITEM-SERVICE
  datasource:
    url: jdbc:postgresql://AAKASH:5432/ItemService
    username: postgres
    password: Akash@Sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  config:
    import: optional:configserver:http://localhost:8588

okta:
  oauth2:
    issuer: https://dev-46450146.okta.com/oauth2/default
    audience: api://default    
   